services:
  mysql:
    image: mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=TubesPP
    ports:
      - 3306:3306
  adminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=dracula
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - 8080:8080
